### ISSUE TITLE
Allocation failure in test

### ISSUE THREAD

**Issue by taylorsw** [Craig-Macomber/lol_alloc#2]
Symptom: unit test fails with"memory allocation of 10 bytes failed".

Repro: Check out the "lol-alloc" branch (seen in this PR: https://github.com/crichards17/Distributed_Id_Allocator/pull/135) and run `cargo test` from the wasm-id-allocator folder.

Let me know what other info you need.

**Comment by Craig-Macomber** [comment]
Use `#[cfg(target_arch = "wasm32")]` to make the use of lol_alloc only apply to the `wasm32` target, or run your tests on the `wasm32` target. The first example in the readme shows this pattern.

Also noted in the readme:

> Supports only wasm32: other targets may build, but the allocators will not work on them (except: FailAllocator, it errors on all platforms just fine).

**Comment by Craig-Macomber** [comment]
I'm assuming the error you are seeing is this one: https://github.com/Craig-Macomber/lol_alloc/blob/ccb85b01ab48ee3bad4f4d516c8f30e38b443578/lol_alloc/src/lib.rs#L44-L49

**Comment by Craig-Macomber** [comment]
I have published version 0.4.0 which should convert your misconfiguration into a compile error instead of a runtime error.

**Comment by taylorsw** [comment]
That was it, thanks!
